#spring:
#  application:
#    name: eureca-server
#server:
#  port: 8081
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8081/eureca-server
#  server:
#    enable-self-preservation: false
#logging:
#  level:
#    com:
#      netflix:
#        eureka: false
#        discovery: false
#  pattern:
#    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#  server:
#    enable-self-preservation: false
logging:
  level:
    com:
      netflix:
        eureka: false
        discovery: false